site_name: Data Builders

site_description: Visão do Produto e Projeto

theme:
  name: material
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-night
        name: "Ativar modo escuro"
    - scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: "Voltar para modo claro"
  font:
    text:  Google Sans Code
    code:  Google Sans Code
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.annotate 
    - content.tabs.link     
    - instant                
    - navigation.expand
    - navigation.index
    - navigation.tracking
  toc:
    depth: 3
    permalink: true
    title: "Índice"
    start_level: 1
    end_level: 2

nav:
  - Home:
    - index.md
    - Equipe: home/equipe.md

  - Projeto:
    - Cenário Atual do Cliente: visao_produto/cenario.md
    - Solução Proposta: visao_produto/solucao.md
    - Estratégias de Engenharia: visao_produto/estrategias.md
    - Técnicas de Engenharia de Requisitos: visao_produto/tecnicas_de_ER.md
    - Cronograma e Entregas: visao_produto/cronograma.md
    - Interação entre Equipe e Cliente: visao_produto/interacao.md
    - Requisitos de Software: visao_produto/requisitos.md
    - DoR e DoD: visao_produto/dor_e_dod.md
    - User Stories: visao_produto/user_stories.md
    - **Casos de Uso: visao_produto/casos_de_uso.md**
    - **Matriz de Rastreabilidade: visao_produto/matriz_rastreabilidade.md**
    - Product Backlog: visao_produto/product_backlog.md
    - Protótipo: visao_produto/prototipo.md
    - Lições Aprendidas: visao_produto/licoes.md
    - Referências Bibliográficas: visao_produto/referencias.md

  - Entregas: 
    - Unidade 1: entregas/unidade1.md
    - Unidade 2: entregas/unidade2.md
markdown_extensions:

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      title: "Conteúdo da página"
      permalink: true
      permalink_title: "Link permanente para esta seção"
      baselevel: 1
      toc_depth: 3
      separator: "-"
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tilde
  - pymdownx.critic